# Generated by Django 4.2.16 on 2025-08-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Home address', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal bio or notes', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='CareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('therapist', 'Therapist'), ('teacher', 'Teacher'), ('support_worker', 'Support Worker'), ('other', 'Other')], default='guardian', max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the care relationship', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autistic_person', models.ForeignKey(limit_choices_to={'role': 'autistic_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships_as_autistic', to=settings.AUTH_USER_MODEL)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_relationships_as_caregiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Relationship',
                'verbose_name_plural': 'Care Relationships',
                'unique_together': {('caregiver', 'autistic_person')},
            },
        ),
    ]
