# Generated by Django 4.2.16 on 2025-08-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0002_alter_customuser_options_customuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the note', max_length=200)),
                ('content', models.TextField(help_text='Detailed note content')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('behavior', 'Behavior Observation'), ('progress', 'Progress Update'), ('concern', 'Concern'), ('achievement', 'Achievement'), ('medication', 'Medication'), ('appointment', 'Appointment'), ('emergency', 'Emergency Contact')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_private', models.BooleanField(default=False, help_text='Private notes only visible to caregivers')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autistic_person', models.ForeignKey(limit_choices_to={'role': 'autistic_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_notes_received', to=settings.AUTH_USER_MODEL)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_notes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Note',
                'verbose_name_plural': 'Care Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_email', models.EmailField(help_text='Email of the caregiver to invite', max_length=254)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('therapist', 'Therapist'), ('teacher', 'Teacher'), ('support_worker', 'Support Worker'), ('other', 'Other')], default='guardian', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invitation_token', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from autistic person', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('autistic_person', models.ForeignKey(limit_choices_to={'role': 'autistic_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_invitations', to=settings.AUTH_USER_MODEL)),
                ('caregiver', models.ForeignKey(blank=True, limit_choices_to={'role': 'caregiver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver Invitation',
                'verbose_name_plural': 'Caregiver Invitations',
            },
        ),
    ]
