# Generated by Django 4.2.16 on 2025-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0002_improve_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='DailyNest_e_timesta_bba4a1_idx',
            old_name='DailyNest_e_timesta_8b5a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='DailyNest_e_face_em_b2ce83_idx',
            old_name='DailyNest_e_face_em_a8c9d1_idx',
        ),
        migrations.RenameIndex(
            model_name='emotionrecord',
            new_name='DailyNest_e_voice_e_f4401d_idx',
            old_name='DailyNest_e_voice_e_b7f2e3_idx',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
