# Generated by Django 5.2.5 on 2025-08-28 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0005_chatmessage_is_bot_chatmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('bubble_pop', 'Bubble Pop'), ('memory_match', 'Memory Match'), ('puzzle_solve', 'Puzzle Solve'), ('calm_colors', 'Calm Colors'), ('breathing_exercise', 'Breathing Exercise')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_played'],
                'indexes': [models.Index(fields=['user', 'game_type'], name='DailyNest_g_user_id_11887a_idx'), models.Index(fields=['last_played'], name='DailyNest_g_last_pl_c55faf_idx')],
                'unique_together': {('user', 'game_type')},
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('bubble_pop', 'Bubble Pop'), ('memory_match', 'Memory Match'), ('puzzle_solve', 'Puzzle Solve'), ('calm_colors', 'Calm Colors'), ('breathing_exercise', 'Breathing Exercise')], max_length=50)),
                ('session_score', models.IntegerField(default=0)),
                ('session_duration', models.IntegerField(default=0, help_text='Session duration in seconds')),
                ('session_data', models.JSONField(blank=True, default=dict, help_text='Additional session data')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'game_type'], name='DailyNest_g_user_id_72e390_idx'), models.Index(fields=['started_at'], name='DailyNest_g_started_1d2ebb_idx')],
            },
        ),
    ]
