# Generated by Django 5.2.5 on 2025-08-28 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0006_gameprogress_gamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('face_done', models.BooleanField(default=False)),
                ('voice_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='DailyNest_d_user_id_139693_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
