# Generated by Django 5.2.5 on 2025-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0007_dailysessionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprogress',
            name='game_type',
            field=models.CharField(choices=[('guess_the_bowl', 'Guess The Bowl'), ('bubble_pop', 'Bubble Pop'), ('breathing_exercise', 'Breathing Exercise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('guess_the_bowl', 'Guess The Bowl'), ('bubble_pop', 'Bubble Pop'), ('breathing_exercise', 'Breathing Exercise')], max_length=50),
        ),
        migrations.DeleteModel(
            name='DailySessionLog',
        ),
    ]
