# Generated by Django 4.2.16 on 2025-08-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0008_alter_gameprogress_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprogress',
            name='game_type',
            field=models.CharField(choices=[('guess_the_bowl', 'Guess The Bowl'), ('bubble_pop', 'Bubble Pop'), ('breathing_exercise', 'Breathing Exercise'), ('colorfill', 'Creative Color Fill'), ('memory_match', 'Happy Memory Match')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('guess_the_bowl', 'Guess The Bowl'), ('bubble_pop', 'Bubble Pop'), ('breathing_exercise', 'Breathing Exercise'), ('colorfill', 'Creative Color Fill'), ('memory_match', 'Happy Memory Match')], max_length=50),
        ),
    ]
