# Generated by Django 4.2.16 on 2025-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0009_alter_gameprogress_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='emotion_check_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (3, 'Every 3 hours'), (6, 'Every 6 hours'), (24, 'Once per day')], default=24, help_text='How often to prompt for emotion check'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_emotion_check',
            field=models.DateTimeField(blank=True, help_text='Last time emotion was checked', null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='skip_emotion_checks',
            field=models.BooleanField(default=False, help_text='Skip automatic emotion checks'),
        ),
    ]
