# Generated by Django 4.2.16 on 2025-08-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0010_userpreference_emotion_check_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='emotion_check_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (3, 'Every 3 hours'), (6, 'Every 6 hours'), (12, 'Every 12 hours'), (24, 'Daily'), (-1, 'Morning only (8-10 AM)'), (-2, 'Every login')], default=24, help_text='How often to prompt for emotion check'),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the journal entry', max_length=200)),
                ('content', models.TextField(help_text='Transcribed content from voice recording')),
                ('audio_file', models.FileField(blank=True, help_text='Original voice recording', null=True, upload_to='journal_audio/')),
                ('transcription_confidence', models.FloatField(blank=True, help_text='Confidence score from Whisper transcription', null=True)),
                ('mood_rating', models.IntegerField(blank=True, choices=[(1, 'Very Sad'), (2, 'Sad'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], help_text='Self-reported mood rating', null=True)),
                ('word_count', models.IntegerField(default=0, help_text='Number of words in the entry')),
                ('is_private', models.BooleanField(default=False, help_text='Hide from caregivers if true')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'autistic_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
