# Generated by Django 4.2.16 on 2025-08-29 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0012_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Original voice recording', null=True, upload_to='journal_audio/'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(blank=True, help_text='Transcribed content from voice recording', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Hide from caregivers if true'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Sad'), (2, 'Sad'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')], help_text='Self-reported mood rating', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the journal entry', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='transcription_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score from Whisper transcription', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'autistic_person'}, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Number of words in the entry'),
        ),
    ]
