# Generated by Django 4.2.16 on 2025-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0013_alter_journalentry_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='caregiver_mode_enabled',
            field=models.BooleanField(default=False, help_text='Whether caregiver mode is set up'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='caregiver_password',
            field=models.CharField(blank=True, help_text='Password for caregiver mode access', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('autistic_person', 'Autistic Person')], default='autistic_person', max_length=20),
        ),
    ]
