# Generated by Django 4.2.16 on 2025-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0014_customuser_caregiver_mode_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='caregiver_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='caregiver_pin',
            field=models.CharField(blank=True, help_text='6-digit PIN for caregiver mode access', max_length=128, null=True),
        ),
    ]
