# Generated by Django 4.2.16 on 2025-08-29 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0015_remove_customuser_caregiver_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulednote',
            options={'ordering': ['scheduled_time', '-priority'], 'verbose_name': 'Scheduled Note', 'verbose_name_plural': 'Scheduled Notes'},
        ),
        migrations.RemoveField(
            model_name='schedulednote',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='schedulednote',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schedulednote',
            name='next_run_time',
        ),
        migrations.RemoveField(
            model_name='schedulednote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='carenote',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carenote',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='emotion',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='emotionrecord',
            name='source',
            field=models.CharField(choices=[('FACE', 'Face Detection'), ('VOICE', 'Voice Analysis'), ('TEXT', 'Text Analysis')], default='FACE', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_name',
            field=models.CharField(default='Unknown Game', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedulednote',
            name='reminder_time',
            field=models.IntegerField(choices=[(15, '15 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (1440, '1 day before')], default=30),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='face_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='voice_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedulednote',
            name='caregiver',
            field=models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_scheduled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulednote',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedulednote',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedulednote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulednote',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
