# Generated by Django 4.2.16 on 2025-08-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0016_alter_schedulednote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carenote',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='carenote',
            name='scheduled_for',
        ),
        migrations.RemoveField(
            model_name='emotionrecord',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='emotionrecord',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='emotionrecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='face_emotion',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('excited', 'Excited'), ('fear', 'Fear'), ('disgust', 'Disgust')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emotionrecord',
            name='voice_emotion',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('excited', 'Excited'), ('fear', 'Fear'), ('disgust', 'Disgust')], max_length=50, null=True),
        ),
    ]
