# Generated by Django 4.2.16 on 2025-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0018_add_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='Token for email verification', null=True),
        ),
    ]
