# Generated by Django 4.2.16 on 2025-08-30 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyNest', '0019_alter_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlannerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Activity title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed activity description')),
                ('activity_type', models.CharField(choices=[('routine', 'Routine'), ('therapy', 'Therapy'), ('learning', 'Learning'), ('play', 'Play'), ('meal', 'Meal'), ('rest', 'Rest'), ('social', 'Social'), ('other', 'Other')], default='routine', max_length=20)),
                ('scheduled_date', models.DateField(help_text='Date when activity is scheduled')),
                ('scheduled_time', models.TimeField(help_text='Time when activity starts')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=15)),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Whether to show reminders')),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15, help_text='Minutes before activity to show reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When activity was marked as completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes added when activity is completed')),
                ('caregiver_notes', models.TextField(blank=True, help_text='Private notes for caregivers')),
                ('assigned_to', models.ForeignKey(help_text='User this activity is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Caregiver who created this activity', on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Planner Activity',
                'verbose_name_plural': 'Daily Planner Activities',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['scheduled_date', 'scheduled_time'], name='DailyNest_d_schedul_0ef092_idx'), models.Index(fields=['assigned_to', 'status'], name='DailyNest_d_assigne_d3c1e8_idx'), models.Index(fields=['activity_type'], name='DailyNest_d_activit_49795c_idx'), models.Index(fields=['priority'], name='DailyNest_d_priorit_7d4cd3_idx')],
            },
        ),
    ]
